name: Checkstyle YAML

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Install checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar -O checkstyle.jar

    - name: Lint YAML files
      run: java -jar checkstyle.jar -c sun_checks.xml .
